config/routes.rb
Rails.application.routes.draw do
  resources :supervisors

  root 'application#helloworld'
  

end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
    
    validates :svname, presence: true
    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def helloworld
    render text: "Hello,World!"
  end  
end

app/controllers/supervisors_controller.rb
class SupervisorsController < ApplicationController
  before_action :set_supervisor, only: [:show, :edit, :update, :destroy]

  # GET /supervisors
  # GET /supervisors.json
  def index
    @supervisors = Supervisor.all
  end

  # GET /supervisors/1
  # GET /supervisors/1.json
  def show
  end

  # GET /supervisors/new
  def new
    @supervisor = Supervisor.new
  end

  # GET /supervisors/1/edit
  def edit
  end

  # POST /supervisors
  # POST /supervisors.json
  def create
    @supervisor = Supervisor.new(supervisor_params)

    respond_to do |format|
      if @supervisor.save
        format.html { redirect_to @supervisor, notice: 'Supervisor was successfully created.' }
        format.json { render :show, status: :created, location: @supervisor }
      else
        format.html { render :new }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supervisors/1
  # PATCH/PUT /supervisors/1.json
  def update
    respond_to do |format|
      if @supervisor.update(supervisor_params)
        format.html { redirect_to @supervisor, notice: 'Supervisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @supervisor }
      else
        format.html { render :edit }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supervisors/1
  # DELETE /supervisors/1.json
  def destroy
    @supervisor.destroy
    respond_to do |format|
      format.html { redirect_to supervisors_url, notice: 'Supervisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supervisor
      @supervisor = Supervisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supervisor_params
      params.require(:supervisor).permit(:svname, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/supervisors/_form.html.erb
<%= form_for(@supervisor) do |f| %>
  <% if @supervisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supervisor.errors.count, "error") %> prohibited this supervisor from being saved:</h2>

      <ul>
      <% @supervisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :svname %><br>
    <%= f.text_field :svname %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supervisors/edit.html.erb
<h1>Editing Supervisor</h1>

<%= render 'form' %>

<%= link_to 'Show', @supervisor %> |
<%= link_to 'Back', supervisors_path %>

app/views/supervisors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Supervisors</h1>

<table>
  <thead>
    <tr>
      <th>Svname</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supervisors.each do |supervisor| %>
      <tr>
        <td><%= supervisor.svname %></td>
        <td><%= supervisor.password_digest %></td>
        <td><%= link_to 'Show', supervisor %></td>
        <td><%= link_to 'Edit', edit_supervisor_path(supervisor) %></td>
        <td><%= link_to 'Destroy', supervisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supervisor', new_supervisor_path %>

app/views/supervisors/new.html.erb
<h1>New Supervisor</h1>

<%= render 'form' %>

<%= link_to 'Back', supervisors_path %>

app/views/supervisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Svname:</strong>
  <%= @supervisor.svname %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @supervisor.password_digest %>
</p>

<%= link_to 'Edit', edit_supervisor_path(@supervisor) %> |
<%= link_to 'Back', supervisors_path %>